CREATE TABLE IF NOT EXISTS phase8_option_instruments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exchange TEXT NOT NULL,
    source TEXT NOT NULL,
    symbol TEXT NOT NULL,
    provider_instrument_id BIGINT,
    underlying TEXT NOT NULL,
    option_type TEXT NOT NULL,
    strike NUMERIC NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    instrument_created_at TIMESTAMPTZ,
    instrument_state TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    price_index TEXT NOT NULL,
    base_currency TEXT NOT NULL,
    quote_currency TEXT NOT NULL,
    settlement_currency TEXT NOT NULL,
    exchange_timestamp TIMESTAMPTZ,
    timestamp_semantics TEXT NOT NULL DEFAULT 'NOT_PROVIDED',
    fetched_at TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL,
    source_fields JSONB NOT NULL DEFAULT '{}'::jsonb,
    raw_reference TEXT,
    CONSTRAINT phase8_option_instruments_exchange_symbol_uq UNIQUE (exchange, symbol),
    CONSTRAINT phase8_option_instruments_provider_id_check
        CHECK (provider_instrument_id IS NULL OR provider_instrument_id > 0),
    CONSTRAINT phase8_option_instruments_underlying_check CHECK (underlying IN ('BTC', 'ETH')),
    CONSTRAINT phase8_option_instruments_option_type_check CHECK (option_type IN ('call', 'put')),
    CONSTRAINT phase8_option_instruments_strike_check CHECK (strike > 0),
    CONSTRAINT phase8_option_instruments_timestamp_semantics_check
        CHECK (timestamp_semantics IN ('VERIFIED', 'UNVERIFIED', 'NOT_PROVIDED')),
    CONSTRAINT phase8_option_instruments_status_check
        CHECK (status IN ('AVAILABLE', 'STALE', 'NOT_AVAILABLE', 'PARTIAL', 'ERROR')),
    CONSTRAINT phase8_option_instruments_source_fields_check
        CHECK (jsonb_typeof(source_fields) = 'object')
);

CREATE INDEX IF NOT EXISTS phase8_option_instruments_lookup_idx
    ON phase8_option_instruments (exchange, underlying, is_active, expires_at);

CREATE TABLE IF NOT EXISTS phase8_option_instrument_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id BIGINT REFERENCES phase8_option_instruments(id) ON DELETE RESTRICT,
    exchange TEXT NOT NULL,
    source TEXT NOT NULL,
    symbol TEXT NOT NULL,
    event_type TEXT NOT NULL,
    instrument_state TEXT NOT NULL,
    event_identity TEXT NOT NULL,
    exchange_timestamp TIMESTAMPTZ,
    timestamp_semantics TEXT NOT NULL DEFAULT 'UNVERIFIED',
    received_at TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL,
    raw_reference TEXT,
    CONSTRAINT phase8_option_instrument_events_identity_uq UNIQUE (exchange, event_identity),
    CONSTRAINT phase8_option_instrument_events_type_check CHECK (event_type IN ('CREATION', 'STATE')),
    CONSTRAINT phase8_option_instrument_events_timestamp_semantics_check
        CHECK (timestamp_semantics IN ('VERIFIED', 'UNVERIFIED', 'NOT_PROVIDED')),
    CONSTRAINT phase8_option_instrument_events_status_check
        CHECK (status IN ('AVAILABLE', 'STALE', 'NOT_AVAILABLE', 'PARTIAL', 'ERROR'))
);

CREATE INDEX IF NOT EXISTS phase8_option_instrument_events_retention_idx
    ON phase8_option_instrument_events (processed_at, id);
CREATE INDEX IF NOT EXISTS phase8_option_instrument_events_symbol_idx
    ON phase8_option_instrument_events (exchange, symbol, received_at DESC);

CREATE TABLE IF NOT EXISTS phase8_option_market_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id BIGINT REFERENCES phase8_option_instruments(id) ON DELETE RESTRICT,
    exchange TEXT NOT NULL,
    source TEXT NOT NULL,
    symbol TEXT NOT NULL,
    underlying TEXT NOT NULL,
    price_index TEXT,
    underlying_index TEXT,
    quote_currency TEXT,
    observation_kind TEXT NOT NULL,
    exchange_timestamp TIMESTAMPTZ,
    timestamp_semantics TEXT NOT NULL,
    fetched_at TIMESTAMPTZ,
    received_at TIMESTAMPTZ,
    processed_at TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL,
    schema_version TEXT NOT NULL,
    metrics JSONB NOT NULL,
    field_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    payload_hash TEXT NOT NULL,
    raw_reference TEXT,
    CONSTRAINT phase8_option_market_snapshots_underlying_check CHECK (underlying IN ('BTC', 'ETH')),
    CONSTRAINT phase8_option_market_snapshots_kind_check CHECK (
        observation_kind IN (
            'REST_CHAIN_SUMMARY',
            'WS_MARKPRICE_SNAPSHOT', 'WS_MARKPRICE_CHANGE',
            'WS_INCREMENTAL_TICKER_SNAPSHOT', 'WS_INCREMENTAL_TICKER_CHANGE'
        )
    ),
    CONSTRAINT phase8_option_market_snapshots_timestamp_semantics_check
        CHECK (timestamp_semantics IN ('VERIFIED', 'UNVERIFIED', 'NOT_PROVIDED')),
    CONSTRAINT phase8_option_market_snapshots_status_check
        CHECK (status IN ('AVAILABLE', 'STALE', 'NOT_AVAILABLE', 'PARTIAL', 'ERROR')),
    CONSTRAINT phase8_option_market_snapshots_metrics_check CHECK (jsonb_typeof(metrics) = 'object'),
    CONSTRAINT phase8_option_market_snapshots_field_metadata_check
        CHECK (jsonb_typeof(field_metadata) = 'object'),
    CONSTRAINT phase8_option_market_snapshots_payload_hash_check
        CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT phase8_option_market_snapshots_capture_time_check CHECK (
        (observation_kind = 'REST_CHAIN_SUMMARY' AND fetched_at IS NOT NULL AND received_at IS NULL)
        OR
        (observation_kind <> 'REST_CHAIN_SUMMARY' AND fetched_at IS NULL AND received_at IS NOT NULL)
    ),
    CONSTRAINT phase8_option_market_snapshots_dedup_uq
        UNIQUE NULLS NOT DISTINCT (exchange, symbol, observation_kind, exchange_timestamp, payload_hash)
);

CREATE INDEX IF NOT EXISTS phase8_option_market_snapshots_summary_retention_idx
    ON phase8_option_market_snapshots (fetched_at, id)
    WHERE observation_kind = 'REST_CHAIN_SUMMARY';
CREATE INDEX IF NOT EXISTS phase8_option_market_snapshots_markprice_retention_idx
    ON phase8_option_market_snapshots (received_at, id)
    WHERE observation_kind IN ('WS_MARKPRICE_SNAPSHOT', 'WS_MARKPRICE_CHANGE');
CREATE INDEX IF NOT EXISTS phase8_option_market_snapshots_ticker_retention_idx
    ON phase8_option_market_snapshots (received_at, id)
    WHERE observation_kind IN ('WS_INCREMENTAL_TICKER_SNAPSHOT', 'WS_INCREMENTAL_TICKER_CHANGE');
CREATE INDEX IF NOT EXISTS phase8_option_market_snapshots_latest_idx
    ON phase8_option_market_snapshots (exchange, symbol, observation_kind, processed_at DESC);

COMMENT ON COLUMN phase8_option_market_snapshots.field_metadata IS
    'Per-field source_field, unit_code, unit_status, status, provenance, field_last_updated_at, exchange_timestamp, capture time, and quality reason.';

CREATE TABLE IF NOT EXISTS phase8_option_context_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    underlying TEXT NOT NULL,
    context_timestamp TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL,
    calculation_version TEXT NOT NULL,
    metrics JSONB NOT NULL,
    source_timestamps JSONB NOT NULL DEFAULT '{}'::jsonb,
    source_capture_times JSONB NOT NULL DEFAULT '{}'::jsonb,
    coverage JSONB NOT NULL DEFAULT '{}'::jsonb,
    provenance JSONB NOT NULL DEFAULT '{}'::jsonb,
    input_observation_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    status TEXT NOT NULL,
    reason_code TEXT,
    unit_contract_version TEXT,
    context_only BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT phase8_option_context_snapshots_underlying_check CHECK (underlying IN ('BTC', 'ETH')),
    CONSTRAINT phase8_option_context_snapshots_metrics_check CHECK (jsonb_typeof(metrics) = 'object'),
    CONSTRAINT phase8_option_context_snapshots_source_timestamps_check
        CHECK (jsonb_typeof(source_timestamps) = 'object'),
    CONSTRAINT phase8_option_context_snapshots_capture_times_check
        CHECK (jsonb_typeof(source_capture_times) = 'object'),
    CONSTRAINT phase8_option_context_snapshots_coverage_check CHECK (jsonb_typeof(coverage) = 'object'),
    CONSTRAINT phase8_option_context_snapshots_provenance_check CHECK (jsonb_typeof(provenance) = 'object'),
    CONSTRAINT phase8_option_context_snapshots_inputs_check
        CHECK (jsonb_typeof(input_observation_ids) = 'array'),
    CONSTRAINT phase8_option_context_snapshots_status_check
        CHECK (status IN ('AVAILABLE', 'STALE', 'NOT_AVAILABLE', 'PARTIAL', 'ERROR')),
    CONSTRAINT phase8_option_context_snapshots_context_only_check CHECK (context_only IS TRUE),
    CONSTRAINT phase8_option_context_snapshots_replay_uq
        UNIQUE (underlying, context_timestamp, calculation_version)
);

CREATE INDEX IF NOT EXISTS phase8_option_context_snapshots_retention_idx
    ON phase8_option_context_snapshots (processed_at, id);
CREATE INDEX IF NOT EXISTS phase8_option_context_snapshots_lookup_idx
    ON phase8_option_context_snapshots (underlying, context_timestamp DESC);

COMMENT ON COLUMN phase8_option_market_snapshots.metrics IS
    'Exact JSON numeric source values keyed by canonical metric; missing values are explicit null/status metadata, never zero-filled.';
COMMENT ON COLUMN phase8_option_context_snapshots.metrics IS
    'Immutable context-only outputs; metric freshness, age, coverage, reason, unit status, and provenance are stored per metric.';
